# See https://docs.espressif.com/projects/idf-build-apps/en/latest/references/config_file.html

config_rules = [
    "sdkconfig.ci.wifi=wifi",
    "sdkconfig.ci.ethernet=ethernet",
    "sdkconfig.ci.tcp=tcp",
    "sdkconfig.ci.ascii=ascii",
    "sdkconfig.ci.rtu=rtu",
    "sdkconfig.ci.serial=serial",
    "sdkconfig.ci.generic=generic",
    "sdkconfig.defaults=default",
    "=default",
]

sdkconfig_defaults = "sdkconfig.defaults"

recursive = true
check_warnings = true
keep_going = true

build_dir = "build_@t_@w"
build_log_filename = "build_log.txt"
size_json_filename = "size.json"

collect_app_info_filename = "app_info_@p.txt"

check_manifest_rules = true
manifest_filepatterns = ["**/.build-test-rules.yml"]
ignore_warning_files = ["tools/ignore_build_warnings.txt"]
